### ISSUE TITLE
Failing Java adapters in 7.0

### ISSUE THREAD

**Issue by nasht00** [andrewferrier/mfp-gitignore#14]
My project worked fine, I added the gitgnore, committed and uploaded.
Then I downloaded it again and imported it. When deploying the Java adapter:

```
Adapter deployment failed: JAXRS Application class: 'com.sample.QRApplication' was not found (or cannot be loaded). 
Make sure that the class name in the adapter's xml file is correct and that the class actually exist in the adapter's bin folder or in one of the jars of the adapter's lib folder [project BinaryResponse]
```

**Comment by nasht00** [comment]
I've tried to add a "gitinclude" inside "lib" - it did not help.
I'm thinking it has to do with the "bin" folder. It included a "classes" folder and a "war" folder in addition to the usual wlapp and adapter files.

**Comment by nasht00** [comment]
Seems like server/java is needed as well. gitkeep solved the issue

**Comment by nickcmaynard** [comment]
`server/java/.gitkeep` is already documented as required in README.md.

I've just:
```
mfp create TestProject
cd TestProject
mfp add adapter TestAdapter -t java -p com.testme
touch server/java/.gitkeep
wget https://raw.githubusercontent.com/andrewferrier/mfp-gitignore/master/MFP_7.0.gitignore
mv MFP_7.0.gitignore .gitignore
git init
git add .
git commit -m 'initial commit'
cd ..
git clone TestProject TestProject-clone
cd TestProject-clone
mfp bd
```

I had a single issue - the `adapters/TestAdapter/lib` directory was missing.  After re-adding it, everything worked as expected.  I'll add documentation to README.md re. Java adapters and their `lib` directories.

In summary, I can't recreate your issue.  Can you provide recreation steps?

**Comment by nasht00** [comment]
I did not see the readme.
I think we're good then.

**Comment by ChaitanyaValluru** [comment]
class files are not getting generated in bin folder in eclipse while running a java adapter..
can anyone suggest what could be the reason..
also tried deleting wlBuildResources folder from Appdata - Local - Temp

**Comment by nickcmaynard** [comment]
Not related to this issue nor appropriate to this project. Please work with MFP support.
