### ISSUE TITLE
backup.zip

### ISSUE THREAD

**Issue by nasht00** [andrewferrier/mfp-gitignore#17]
Studio sometimes creates a file names MyProject_timestamp.backup.zip

Maybe we could add a rule to ignore *.backup.zip ?

**Comment by nickcmaynard** [comment]
@nasht00 Good idea.  Can you submit a PR against the templates?  Please make sure the rule is appropriately scoped to the root of the project (leading `/`).

**Comment by andrewferrier** [comment]
Covered in pull request #18. Closing as duplicate.
