### ISSUE TITLE
Merge in Eclipse .gitignore

### ISSUE THREAD

**Issue by andrewferrier** [andrewferrier/mfp-gitignore#6]
Merge in content from https://github.com/github/gitignore/blob/master/Global/Eclipse.gitignore as applicable.

**Comment by nickcmaynard** [comment]
I'm not sure this is a good idea - .project, .classpath etc. ISTR are pretty essential to Eclipse functioning?

**Comment by andrewferrier** [comment]
That's a very good point. I hadn't looked at that file carefully enough. Let's can that idea.
