### ISSUE TITLE
Should ignore patterns include a leading slash?

### ISSUE THREAD

**Issue by nickcmaynard** [andrewferrier/mfp-gitignore#7]
The majority of our ignore patterns (certainly, those beginning with "app") should probably begin with a / to prevent recursive matching.

This probably isn't a real issue, but would be more technically "correct".

OTOH, the "bin" match should probably remain recursive.  Perhaps some documentation comments to explain why certain rules are/aren't recursive?

**Comment by andrewferrier** [comment]
Agreed. I have created a pull request for this and assigned it you - if you're happy, can you hit "merge"?
